CREATE DATABASE IF NOT EXISTS cashcue_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cashcue_db;

CREATE TABLE IF NOT EXISTS user_profiles (
  session_key VARCHAR(128) PRIMARY KEY,
  income DECIMAL(10,2) DEFAULT 0,
  needs DECIMAL(10,2) DEFAULT 0,
  savings DECIMAL(10,2) DEFAULT 0,
  emergency_fund DECIMAL(10,2) DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_profile_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_key VARCHAR(128) NOT NULL,
  income DECIMAL(10,2) DEFAULT 0,
  needs DECIMAL(10,2) DEFAULT 0,
  savings DECIMAL(10,2) DEFAULT 0,
  emergency_fund DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS commitments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_key VARCHAR(128) NOT NULL,
  name VARCHAR(100) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  category VARCHAR(50) NOT NULL,
  is_active TINYINT(1) DEFAULT 1,
  deleted_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS goals (
  session_key VARCHAR(128) PRIMARY KEY,
  name VARCHAR(100) DEFAULT '',
  target DECIMAL(10,2) DEFAULT 0,
  saved DECIMAL(10,2) DEFAULT 0,
  timeline INT DEFAULT 1,
  unit VARCHAR(20) DEFAULT 'months',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS goal_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_key VARCHAR(128) NOT NULL,
  name VARCHAR(100) NOT NULL,
  target DECIMAL(10,2) DEFAULT 0,
  saved DECIMAL(10,2) DEFAULT 0,
  timeline INT DEFAULT 1,
  unit VARCHAR(20) DEFAULT 'months',
  is_active TINYINT(1) DEFAULT 1,
  deleted_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS new_commitments (
  session_key VARCHAR(128) PRIMARY KEY,
  name VARCHAR(100) DEFAULT '',
  amount DECIMAL(10,2) DEFAULT 0,
  duration INT DEFAULT 1,
  unit VARCHAR(20) DEFAULT 'months',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS commitment_checks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_key VARCHAR(128) NOT NULL,
  name VARCHAR(100) NOT NULL,
  amount DECIMAL(10,2) DEFAULT 0,
  duration INT DEFAULT 1,
  unit VARCHAR(20) DEFAULT 'months',
  decision VARCHAR(50),
  score INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
